// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'example_apiKey',
    appId: '1:1234567890:web:example',
    messagingSenderId: '1234567890',
    projectId: 'example-project',
    authDomain: 'example-project.firebaseapp.com',
    storageBucket: 'example-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'example_apiKey',
    appId: '1:1234567890:android:example',
    messagingSenderId: '1234567890',
    projectId: 'example-project',
    storageBucket: 'example-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'example_apiKey',
    appId: '1:1234567890:ios:example',
    messagingSenderId: '1234567890',
    projectId: 'example-project',
    storageBucket: 'example-project.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'example_apiKey',
    appId: '1:1234567890:ios:example',
    messagingSenderId: '1234567890',
    projectId: 'example-project',
    storageBucket: 'example-project.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'example_apiKey',
    appId: '1:1234567890:web:example',
    messagingSenderId: '1234567890',
    projectId: 'example-project',
    authDomain: 'example-project.firebaseapp.com',
    storageBucket: 'example-project.appspot.com',
  );
}
